import type { Lead } from './types';

export const LOOKALIKE_DOMAINS = [
  { domain: 'plaid.com', company: 'Plaid' },
  { domain: 'adyen.com', company: 'Adyen' },
  { domain: 'square.com', company: 'Square' },
  { domain: 'brex.com', company: 'Brex' },
  { domain: 'marqeta.com', company: 'Marqeta' },
  { domain: 'checkout.com', company: 'Checkout.com' },
];

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-1',
    company: 'Plaid',
    domain: 'plaid.com',
    name: 'Zach Perret',
    title: 'CEO',
    linkedinUrl: 'https://linkedin.com/in/zachperret',
    email: 'zach.perret@plaid.com',
    emailStatus: 'verified',
  },
  {
    id: 'lead-2',
    company: 'Plaid',
    domain: 'plaid.com',
    name: 'Eric Sager',
    title: 'VP Engineering',
    linkedinUrl: 'https://linkedin.com/in/ericsager',
    email: 'eric.sager@plaid.com',
    emailStatus: 'verified',
  },
  {
    id: 'lead-3',
    company: 'Adyen',
    domain: 'adyen.com',
    name: 'Pieter van der Does',
    title: 'CEO',
    linkedinUrl: 'https://linkedin.com/in/pietervanderdoes',
    email: 'pieter.vd@adyen.com',
    emailStatus: 'verified',
  },
  {
    id: 'lead-4',
    company: 'Adyen',
    domain: 'adyen.com',
    name: 'Kamran Zaki',
    title: 'COO',
    linkedinUrl: 'https://linkedin.com/in/kamranzaki',
    email: '',
    emailStatus: 'missing',
  },
  {
    id: 'lead-5',
    company: 'Square',
    domain: 'square.com',
    name: 'Amrita Ahuja',
    title: 'CFO',
    linkedinUrl: 'https://linkedin.com/in/amritaahuja',
    email: 'amrita.ahuja@squareup.com',
    emailStatus: 'unverified',
  },
  {
    id: 'lead-6',
    company: 'Brex',
    domain: 'brex.com',
    name: 'Pedro Franceschi',
    title: 'CEO',
    linkedinUrl: 'https://linkedin.com/in/pedrofranceschi',
    email: 'pedro@brex.com',
    emailStatus: 'verified',
  },
  {
    id: 'lead-7',
    company: 'Brex',
    domain: 'brex.com',
    name: 'Michael Tannenbaum',
    title: 'CFO',
    linkedinUrl: 'https://linkedin.com/in/michaeltannenbaum',
    email: 'm.tannenbaum@brex.com',
    emailStatus: 'verified',
  },
  {
    id: 'lead-8',
    company: 'Marqeta',
    domain: 'marqeta.com',
    name: 'Simon Khalaf',
    title: 'CEO',
    linkedinUrl: 'https://linkedin.com/in/simonkhalaf',
    email: '',
    emailStatus: 'skipped',
  },
  {
    id: 'lead-9',
    company: 'Checkout.com',
    domain: 'checkout.com',
    name: 'Guillaume Pousaz',
    title: 'CEO',
    linkedinUrl: 'https://linkedin.com/in/guillaumepousaz',
    email: 'guillaume@checkout.com',
    emailStatus: 'verified',
  },
  {
    id: 'lead-10',
    company: 'Checkout.com',
    domain: 'checkout.com',
    name: 'Meron Colbeci',
    title: 'CTO',
    linkedinUrl: 'https://linkedin.com/in/meroncolbeci',
    email: 'meron.c@checkout.com',
    emailStatus: 'unverified',
  },
];

export function getLogMessages(domain: string, sandboxMode: boolean) {
  const domains = LOOKALIKE_DOMAINS.map((d) => d.domain);

  return {
    sourcing: [
      { delay: 300, level: 'info' as const, message: `Initializing Ocean.io API connection...` },
      { delay: 800, level: 'info' as const, message: `Querying Ocean.io for lookalikes of "${domain}"` },
      { delay: 1400, level: 'info' as const, message: `Filters applied: size=50-500, market=fintech, industry=payments` },
      { delay: 2000, level: 'success' as const, message: `Found ${domains.length} similar domains: ${domains.join(', ')}` },
      { delay: 2400, level: 'info' as const, message: `Sourcing stage complete. Passing ${domains.length} domains to Prospeo.` },
    ],
    decisionMakers: [
      { delay: 300, level: 'info' as const, message: `Initializing Prospeo API for decision-maker lookup...` },
      { delay: 800, level: 'info' as const, message: `Scanning plaid.com for C-suite & VP-level contacts...` },
      { delay: 1400, level: 'success' as const, message: `Found 2 executives at Plaid` },
      { delay: 1800, level: 'info' as const, message: `Scanning adyen.com for decision-makers...` },
      { delay: 2200, level: 'warn' as const, message: `Prospeo rate limit hit (429). Backing off for 2s...` },
      { delay: 2600, level: 'info' as const, message: `Rate limit cleared. Retrying adyen.com...` },
      { delay: 3000, level: 'success' as const, message: `Found 2 executives at Adyen` },
      { delay: 3300, level: 'info' as const, message: `Scanning square.com, brex.com, marqeta.com, checkout.com...` },
      { delay: 3800, level: 'success' as const, message: `Discovered ${MOCK_LEADS.length} total decision-makers across ${domains.length} companies` },
    ],
    emailResolution: [
      { delay: 300, level: 'info' as const, message: `Connecting to Eazyreach email resolution service...` },
      { delay: 700, level: 'info' as const, message: `Resolving LinkedIn URLs to corporate emails...` },
      { delay: 1200, level: 'success' as const, message: `Verified: zach.perret@plaid.com ✓` },
      { delay: 1500, level: 'success' as const, message: `Verified: pieter.vd@adyen.com ✓` },
      { delay: 1800, level: 'warn' as const, message: `Skipped: Kamran Zaki (Adyen) — LinkedIn profile missing email data` },
      { delay: 2100, level: 'warn' as const, message: `Unverified: amrita.ahuja@squareup.com — MX record check inconclusive` },
      { delay: 2400, level: 'success' as const, message: `Verified: pedro@brex.com ✓` },
      { delay: 2600, level: 'warn' as const, message: `Skipped: Simon Khalaf (Marqeta) — No email found, profile is private` },
      { delay: 2900, level: 'info' as const, message: `Resolution complete. 5 verified, 2 unverified, 2 missing/skipped, 1 catch-all` },
    ],
    outreach: sandboxMode
      ? [
          { delay: 300, level: 'warn' as const, message: `🧪 SANDBOX MODE ACTIVE — Emails redirected to test inbox` },
          { delay: 700, level: 'info' as const, message: `Connecting to Brevo transactional API...` },
          { delay: 1100, level: 'info' as const, message: `Sending email 1/8 → test-inbox@autoreach.dev (redirected from zach.perret@plaid.com)` },
          { delay: 1500, level: 'info' as const, message: `Sending email 2/8 → test-inbox@autoreach.dev (redirected from pieter.vd@adyen.com)` },
          { delay: 1900, level: 'success' as const, message: `All 8 emails sent to sandbox inbox. No live emails dispatched.` },
          { delay: 2200, level: 'success' as const, message: `🎉 Pipeline complete (Sandbox Mode). Check test-inbox@autoreach.dev.` },
        ]
      : [
          { delay: 300, level: 'info' as const, message: `Connecting to Brevo transactional API...` },
          { delay: 700, level: 'info' as const, message: `Composing personalized outreach for 8 verified leads...` },
          { delay: 1100, level: 'info' as const, message: `Sending email 1/8 → zach.perret@plaid.com` },
          { delay: 1400, level: 'info' as const, message: `Sending email 2/8 → eric.sager@plaid.com` },
          { delay: 1700, level: 'info' as const, message: `Sending email 3/8 → pieter.vd@adyen.com` },
          { delay: 2000, level: 'success' as const, message: `All 8 emails dispatched successfully via Brevo.` },
          { delay: 2300, level: 'success' as const, message: `🎉 Pipeline complete. Campaign launched for "${domain}" lookalikes.` },
        ],
  };
}
